apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-alertmanager
  namespace: default
  labels:
    app: alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.example.com:587'
      smtp_from: 'alertmanager@example.com'
      smtp_auth_username: 'your_email@example.com'
      smtp_auth_password: 'your_email_password'
      smtp_require_tls: true
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      receiver: 'email-notifications'
    receivers:
      - name: 'email-notifications'
        email_configs:
          - to: 'recipient@example.com'
            send_resolved: true
