global:
  scrape_interval: 15s  # How often Prometheus scrapes targets

scrape_configs:
  - job_name: "api-monitoring"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["your-api-service:8000"]
